# Generated by Django 4.1 on 2024-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='username', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('normal', 'normal'), ('critical', 'critical'), ('severe', 'severe')], max_length=20),
        ),
    ]
