# Generated by Django 4.1 on 2024-06-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0007_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('severe', 'severe'), ('normal', 'normal'), ('critical', 'critical')], max_length=20),
        ),
    ]
