# Generated by Django 4.1 on 2024-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0009_alter_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('normal', 'normal'), ('critical', 'critical'), ('severe', 'severe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(choices=[('earthquake_location', 'earthquake_location'), ('air_quality', 'air_quality')], max_length=100),
        ),
    ]
